# CI definition builds, tests, and creates executable for various
# target platforms including macos, windows, and linux
#
# Build server has following software dependencies.
#
# Software
# - go
image: golang:1.15
stages:
  # build debug/production application and tests
  - builds
  # run application unit and system tests
  - tests
  # create application release based on git tags
  - release

build:
  stage: builds
  script:
    - make

test:
    stage: tests
    script:
      - make test

all:
  stage: release
  rules:
    # only upload artifact on tagged branch (only default branch should ever be tagged)
    - if: $CI_COMMIT_TAG
  script:
    - apt-get update -y
    - apt-get install bzip2 -y
    - make release
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/bins/**
